services:
  db_student_money:
    image: 'postgres:latest'
    container_name: db_student_money
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db_student_money
    networks:
      - postgres-network
    volumes:
      - ./postgres-data/student_money:/var/lib/postgresql/data

  db_email:
    image: 'postgres:latest'
    container_name: db_email
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db_email
    networks:
      - postgres-network
    volumes:
      - ./postgres-data/email:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - db_student_money
      - db_email
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  postgres-network:
    driver: bridge

volumes:
  rabbitmq_data: